function generateReport(analysis) {

    return `
==============================

VELORA AI BUSINESS REPORT

==============================

SUMMARY

${analysis.summary}


------------------------------

BUSINESS PROBLEMS

${analysis.problems.map((item, index) =>
`${index + 1}. ${item}`).join("\n")}


------------------------------

GROWTH OPPORTUNITIES

${analysis.opportunities.map((item, index) =>
`${index + 1}. ${item}`).join("\n")}


------------------------------

RECOMMENDATIONS

${analysis.recommendations.map((item, index) =>
`${index + 1}. ${item}`).join("\n")}


==============================

Generated by Velora AI

==============================
`;

}

module.exports = generateReport;